version : "2"
services:
    frontend:
        build: frontend
        image: frontend
        ports:
            - "8085:80"
        container_name: Engelbart
        networks:
            - backend
        environment:
            - API_HOST=192.168.2.43
            - API_PORT=3000
    db:
        image: mongo
        networks:
            - backend
        container_name: Hopper
        ports:
            - "27018:27017"
    backend:
        build: backend
        image: backend
        ports:
            - "3000:3000"
        networks:
            - backend
        links:
            - db
        container_name: Ritchie
        depends_on:
            - db
        restart: always
        environment:
            - PORT=3000
            - MONGO_HOST=192.168.2.43
            - MONGO_PORT=27018
networks:
    backend:
        driver: "bridge"

