version : "2"
services:
    frontend:
        build: frontend
        ports:
            - "8085:80"
        networks:
            - backend
    db:
        image: mongo
        networks:
            - backend
        ports:
            - "27017:27017"
    backend:
        build: backend
        ports:
            - "3000:3000"
        networks:
            - backend
        links:
            - db
        depends_on:
            - db
        restart: always
        environment:
            - PORT=3000
            - MONGO_HOST=192.168.2.43
            - MONGO_PORT=27017
networks:
    backend:
        driver: "bridge"

